server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Все маршруты → Flutter SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксируем /api/* → backend-сервис в кластере
    location /api/ {
        proxy_pass http://eventhub-backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
